name: Run Postman Collection

on:
  push:
    branches:
      - main

jobs:
  postman-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Newman (CLI de Postman)
        run: npm install -g newman

      - name: Run Postman collection
        run: newman run C:\Pruebas Postman Manu\Prueba Manu.postman_collection.json -r html,cli
